/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dto.ClienteDTO;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import service.ClienteService;

/**
 *
 * @author Daniel
 */
public class ViewSelecionarCliente extends javax.swing.JFrame {    
    private iListener listener;
    

    /**
     * Creates new form ServicosFrame
     */
    
    private ClienteDTO clienteDTO;
    private ArrayList<ClienteDTO> ListaClientes;
    private boolean clienteSelecionado;
    
    /**
     * Creates new form ViewSelecionarProduto
     */
    public ViewSelecionarCliente() {
        initComponents();
        atualizaGrid();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLayout(null);
        setLocationRelativeTo(null);        
    }
    
    public ViewSelecionarCliente(iListener listerner) {
        this.listener = listerner;
        initComponents();
        atualizaGrid();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLayout(null);
        setLocationRelativeTo(null);    
    }
    
    public void atualizaGrid(){
      try {
        ListaClientes = (ArrayList<ClienteDTO>) ClienteService.buscaClientes();

        String[] colunas = {"Nome", "Telefone", "Email"};
        DefaultTableModel modelo = new DefaultTableModel(colunas, 0){
            //Adicionado para não deixar alterar as células da tabela        
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false; 
                }
        };

        for (ClienteDTO cliente : ListaClientes) {
            Object[] linha = {
                cliente.getNome(),
                cliente.getTelefone(),
                cliente.getEmail()
            };
            modelo.addRow(linha);
            
            
        }
        
        

        tbClientes.setModel(modelo);

        } catch (Exception ex) {
            ex.printStackTrace(); // ou exibir uma mensagem de erro em uma dialog
        }
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbClientes = new javax.swing.JTable();
        btAdicionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbClientes);

        btAdicionar.setText("Adicionar");
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 807, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
        int selectedRow = tbClientes.getSelectedRow();
        if (selectedRow != -1) {
            //Object codObj     = tbClientes.getValueAt(selectedRow, 0);
            Object nomeObj = tbClientes.getValueAt(selectedRow, 0);//nome do cliente

            //int cod        = (int) codObj;
            String nome    = (String) nomeObj;
            listener.Cliente(1, nome);
        }
        // fecha janela ao criar no botão
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dispose(); // Ensure the current instance of ServicoFrame is closed
            }
        });
    }//GEN-LAST:event_btAdicionarActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbClientes;
    // End of variables declaration//GEN-END:variables
}
