/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dto.ProdutoDTO;
import java.util.ArrayList;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import service.ProdutoService;

/**
 *
 * @author Daniel
 */
public class ViewSelecionarProduto extends javax.swing.JFrame {
    private iListener listener;

    private ProdutoDTO produtoDTO;
    private ArrayList<ProdutoDTO> listaProdutos;
    private boolean produtoSelecionado;
    
    /**
     * Creates new form ViewSelecionarProduto
     */
    public ViewSelecionarProduto() {
        initComponents();
        atualizaGrid();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLayout(null);
        setLocationRelativeTo(null); 
    }
 
    public ViewSelecionarProduto(iListener listerner) {
        this.listener = listerner;
        atualizaGrid();
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLayout(null);
        setLocationRelativeTo(null);    
    }    
    
    public void atualizaGrid(){
      try {
        listaProdutos = (ArrayList<ProdutoDTO>) ProdutoService.buscaProdutos();

        String[] colunas = {"Descrição", "Valor", "Categoria"};
        DefaultTableModel modelo = new DefaultTableModel(colunas, 0);

        for (ProdutoDTO produto : listaProdutos) {
            Object[] linha = {
                produto.getDescricao(),
                produto.getValor(),
                produto.getCategoria()
            };
            modelo.addRow(linha);
        }

        tbProdutos.setModel(modelo);

        } catch (Exception ex) {
            ex.printStackTrace(); // ou exibir uma mensagem de erro em uma dialog
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbProdutos = new javax.swing.JTable();
        btAdicionar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tfQuantidade = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbProdutos);

        btAdicionar.setText("Adicionar");
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Quantidade:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 807, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(tfQuantidade)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
        int selectedRow = tbProdutos.getSelectedRow();
        if (selectedRow != -1) {
            //Object codObj     = tbClientes.getValueAt(selectedRow, 0);
            Object nomeObj  = tbProdutos.getValueAt(selectedRow, 0);//nome do cliente
            Object valorObj = tbProdutos.getValueAt(selectedRow, 1);

            //int cod        = (int) codObj;
            String nome    = (String) nomeObj;
            double valor   = ((Number) valorObj).doubleValue();
            double qtd     = Double.parseDouble(tfQuantidade.getText());
            listener.Produto(1, nome, valor, qtd);
        }
        // fecha janela ao criar no botão
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dispose(); // Ensure the current instance of ServicoFrame is closed
            }
        });
    }//GEN-LAST:event_btAdicionarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbProdutos;
    private javax.swing.JTextField tfQuantidade;
    // End of variables declaration//GEN-END:variables
}
